<?php
/**
 * @var string $link
 */
?>
<div class="mb-3 w-25">
    <label for="userEmail" class="form-label">Enter your email address</label>
    <input type="email" class="form-control" id="userEmail" aria-describedby="userEmailHelp" placeholder="example@domain.com">
    <div id="userEmailHelp" class="form-text">We'll never share your email with anyone else.</div>
    <div id="userEmailServices" class="form-text d-flex justify-content-center">
        <a class="btn btn-light" href="<?= $link ?>">Google</a>
    </div>
</div>