<?php
/**
 * @var string $page
 */
?>
<!Doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <title>User Account <?= $page ?></title>
    <link rel="icon" type="image/x-icon" href="../images/icons/favicon.ico">

    <link rel="stylesheet" href="../css/bootstrap.css"/>
</head>
<body class="bg-dark text-light vh-100 overflow-hidden">

<?php include "$page/overview.phtml" ?>

<script src="../js/jquery-3.6.0.js"></script>
<script src="../js/bootstrap.bundle.js"></script>
</body>
</html>
